"""test

Revision ID: 1dbf4d1484d4
Revises: 45c0548f96e8
Create Date: 2022-05-04 16:08:18.591020

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '1dbf4d1484d4'
down_revision = '45c0548f96e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    main_archive = PGFunction(
        schema="main",
        signature="archive(table_name text)",
        definition="returns int as $$\ndeclare\nDECLARE\n    source text \\:= 'main.' || table_name;\n    sink text \\:= 'archive.' || table_name;\n    stmt text;\n\nBEGIN\n        stmt \\:= 'with\n        archive_all as\n            (delete from ' || source || ' src\n             where exists (select null from ' || source || ') returning src.*)\n        insert into ' || sink || ' select * from archive_all';\n\n    execute stmt;\nEND;\n$$\nLANGUAGE 'plpgsql'"
    )
    op.create_entity(main_archive)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    main_archive = PGFunction(
        schema="main",
        signature="archive(table_name text)",
        definition="returns int as $$\ndeclare\nDECLARE\n    source text \\:= 'main.' || table_name;\n    sink text \\:= 'archive.' || table_name;\n    stmt text;\n\nBEGIN\n        stmt \\:= 'with\n        archive_all as\n            (delete from ' || source || ' src\n             where exists (select null from ' || source || ') returning src.*)\n        insert into ' || sink || ' select * from archive_all';\n\n    execute stmt;\nEND;\n$$\nLANGUAGE 'plpgsql'"
    )
    op.drop_entity(main_archive)

    # ### end Alembic commands ###
