"""init

Revision ID: 45c0548f96e8
Revises: 
Create Date: 2022-05-04 09:04:44.066103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c0548f96e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    op.execute("""
    create schema main;
    create schema archive;
    """)

    op.create_table('test_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('some_column', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('test_table_arch',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('some_column', sa.Integer(), nullable=True),
    schema='archive'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table_arch', schema='archive')
    op.drop_table('test_table', schema='main')

    op.execute("""
    drop schema archive;
    drop schema main;
    """)
    # ### end Alembic commands ###
